/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Site { 
    departmentOid: string;
    organizationOid: string;
    siteAddress?: string;
    siteCode: string;
    siteJson?: string;
    siteName: string;
    siteOid: string;
    siteStatus: string;
    siteUrl?: string;
}
