/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


 export interface SubSite { 
    departmentOid: string;
    organizationOid: string;
    subSiteAddress?: string;
    subSiteJson?: string;
    subSiteName: string;
    subSiteStatus: string;
    subSiteUrl?: string;
    subSiteOid: string;
    siteOid: string;
}